addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.5")
addSbtPlugin("com.geirsson"              % "sbt-scalafmt"        % "1.5.1")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.3.21")
addSbtPlugin("io.github.davidmweber"     % "flyway-sbt"          % "5.2.0")
